import type { WordEntry } from "./types";

export const W: Record<string, WordEntry> = {
  ephemeral: {
    w: "ephemeral",
    ph: "/ɪˈfem.ər.əl/",
    pos: "adjective",
    d: [
      "Lasting for a very short time; transitory by nature.",
      "(Biology) Existing only briefly, within a single season.",
    ],
    ex: [
      "Internet fame is ephemeral — here today, gone by tomorrow.",
      "The morning dew was ephemeral, vanishing before most people woke up.",
      "She captured ephemeral moments of joy in her photography.",
    ],
    us: "Americans say short-lived or it faded fast instead of ephemeral.",
    uk: "British speakers say it did not last long — ephemeral is more literary in the UK.",
    syn: ["fleeting", "transient", "momentary", "brief", "short-lived"],
    fact: "From Greek ephemeros — epi (on) + hemera (day). Ancient Greeks used it for insects that lived only one day.",
    source: "lexicon",
  },
  serendipity: {
    w: "serendipity",
    ph: "/ˌser.ənˈdɪp.ɪ.ti/",
    pos: "noun",
    d: [
      "The occurrence of events by chance in a happy or beneficial way.",
      "The gift of finding valuable things that were not sought.",
    ],
    ex: [
      "Meeting my best friend on that random flight was pure serendipity.",
      "The discovery of penicillin was a famous act of scientific serendipity.",
      "Their love story began with a serendipitous mix-up at the coffee shop.",
    ],
    us: "Americans say it was meant to be or what a happy accident.",
    uk: "British speakers say what a stroke of luck — serendipity is beloved but slightly formal.",
    syn: ["luck", "fortune", "chance", "coincidence", "fate"],
    fact: "Coined by Horace Walpole in 1754, inspired by a Persian fairy tale set in Serendip — the old name for Sri Lanka.",
    source: "lexicon",
  },
  meticulous: {
    w: "meticulous",
    ph: "/məˈtɪk.jʊ.ləs/",
    pos: "adjective",
    d: [
      "Showing great attention to detail; very careful and precise.",
      "Originally meaning fearful — from its Latin root meticulosus.",
    ],
    ex: [
      "She was meticulous about every comma in her manuscript.",
      "The surgeon's meticulous technique reduced recovery time significantly.",
      "He kept meticulous records of every expense, down to the last cent.",
    ],
    us: "Americans say super detail-oriented or very thorough.",
    uk: "British people say painstaking or precise to a fault.",
    syn: ["precise", "thorough", "careful", "exact", "fastidious"],
    fact: "From Latin meticulosus meaning fearful — so careful they must be afraid of any mistake.",
    source: "lexicon",
  },
  liminal: {
    w: "liminal",
    ph: "/ˈlɪm.ɪ.nəl/",
    pos: "adjective",
    d: [
      "Relating to a transitional stage; occupying a position on both sides of a boundary.",
      "(Psychology) Relating to the threshold of a physiological or psychological response.",
    ],
    ex: [
      "The weeks between jobs felt deeply liminal — not quite past, not yet future.",
      "Empty airports at 3am have an eerie liminal quality.",
      "Adolescence is the ultimate liminal phase.",
    ],
    us: "Americans use liminal online for creepy-familiar empty spaces like empty malls at night.",
    uk: "British speakers use it academically — in architecture and literary criticism.",
    syn: ["transitional", "threshold", "intermediate", "borderline", "in-between"],
    fact: "Exploded in internet culture through liminal spaces — eerily familiar empty places that feel outside of time.",
    source: "lexicon",
  },
  melancholy: {
    w: "melancholy",
    ph: "/ˈmel.ənˌkɒl.i/",
    pos: "noun",
    d: [
      "A deep, persistent sadness — thoughtful rather than desperate.",
      "A feeling of pensive sadness, typically with no obvious cause.",
    ],
    ex: [
      "There was a sweet melancholy to the last day of summer.",
      "He played melancholy jazz pieces that made the room go quiet.",
      "She felt a quiet melancholy watching her childhood home disappear.",
    ],
    us: "Americans say I am in my feels or feeling blue.",
    uk: "British speakers love melancholy — a bit melancholy is a perfectly British expression.",
    syn: ["sadness", "gloom", "sorrow", "wistfulness", "pensiveness"],
    fact: "From Greek melan (black) + khole (bile). Ancient Greeks believed black bile caused sadness.",
    source: "lexicon",
  },
  wanderlust: {
    w: "wanderlust",
    ph: "/ˈwɒn.dəˌlʌst/",
    pos: "noun",
    d: [
      "A strong desire to travel and explore the world.",
      "A restless craving for adventure in unfamiliar places.",
    ],
    ex: [
      "Her wanderlust took her to 47 countries before she turned 30.",
      "Scrolling travel photos at 2am is what wanderlust does to you.",
      "He quit his corporate job because the wanderlust became impossible to ignore.",
    ],
    us: "Americans say I have the travel bug or I need to get out of here.",
    uk: "British speakers use it freely — fits the tradition of explorers and gap year culture.",
    syn: ["restlessness", "travel bug", "roaming spirit", "itchy feet", "adventurousness"],
    fact: "Direct borrowing from German — wandern (to hike) + Lust (desire). Entered English in the early 1900s.",
    source: "lexicon",
  },
  nostalgia: {
    w: "nostalgia",
    ph: "/nɒˈstæl.dʒə/",
    pos: "noun",
    d: [
      "A sentimental longing for a period in the past, associated with happy memories.",
      "Something done or presented to evoke feelings of the past.",
    ],
    ex: [
      "The smell of crayons hits me with an overwhelming wave of nostalgia.",
      "That 90s playlist was pure nostalgia for anyone who grew up in that era.",
      "She felt nostalgia for a version of her life she was not sure had actually existed.",
    ],
    us: "Americans say that gives me all the feels or throwback vibes.",
    uk: "British speakers say makes me feel proper nostalgic — nostalgia runs deep in British culture.",
    syn: ["longing", "sentimentality", "wistfulness", "homesickness", "reminiscence"],
    fact: "Originally a medical diagnosis from 1688 — Swiss soldiers were officially diagnosed with it as a dangerous illness.",
    source: "lexicon",
  },
  resilience: {
    w: "resilience",
    ph: "/rɪˈzɪl.i.əns/",
    pos: "noun",
    d: [
      "The capacity to recover quickly from difficulties; toughness.",
      "(Physics) The ability of a substance to spring back into shape.",
    ],
    ex: [
      "Her resilience after losing everything inspired everyone around her.",
      "Cities need resilience built into their infrastructure for climate disasters.",
      "Children show remarkable resilience when given the right support.",
    ],
    us: "Americans say bounce back ability or mental toughness — huge in US self-help culture.",
    uk: "British speakers might say grit or stiff upper lip in casual conversation.",
    syn: ["toughness", "adaptability", "grit", "durability", "strength"],
    fact: "Originally a physics term. Psychologists adopted it in the 1970s. Now one of the most used words in mental health.",
    source: "lexicon",
  },
  euphoria: {
    w: "euphoria",
    ph: "/juːˈfɔː.ri.ə/",
    pos: "noun",
    d: [
      "A feeling of intense excitement and happiness; an overwhelming sense of well-being.",
      "(Medicine) A feeling of happiness that may be exaggerated and not well-founded.",
    ],
    ex: [
      "Crossing the finish line sent a rush of euphoria through her body.",
      "The crowd euphoria at the concert was something she had never felt before.",
      "Post-workout euphoria is real — it is the endorphins talking.",
    ],
    us: "Americans say I am on cloud nine — euphoria is also a popular TV show now.",
    uk: "British speakers say over the moon or absolutely buzzing.",
    syn: ["elation", "joy", "ecstasy", "bliss", "exhilaration"],
    fact: "From Greek euphoros meaning healthy. It entered medicine first — describing an abnormal sense of well-being.",
    source: "lexicon",
  },
  ethereal: {
    w: "ethereal",
    ph: "/ɪˈθɪə.ri.əl/",
    pos: "adjective",
    d: [
      "Extremely delicate and light in a way that seems too perfect for this world.",
      "(Old science) Relating to the regions beyond the earth; celestial.",
    ],
    ex: [
      "Her voice had an ethereal quality that silenced the entire room.",
      "The morning fog gave the forest an ethereal, dreamlike appearance.",
      "The aurora borealis is one of the most ethereal sights on Earth.",
    ],
    us: "Americans use ethereal in music and art — she has this ethereal energy is a real compliment.",
    uk: "British speakers love it in literary and poetic contexts.",
    syn: ["delicate", "otherworldly", "celestial", "gossamer", "luminous"],
    fact: "Related to ether — the ancient fifth element believed to fill the heavens. Disproven by Einstein, but the word stayed beautiful.",
    source: "lexicon",
  },
  tenacious: {
    w: "tenacious",
    ph: "/tɪˈneɪ.ʃəs/",
    pos: "adjective",
    d: [
      "Tending to keep a firm hold; not giving up easily.",
      "Not readily relinquishing a position or course of action; persistent.",
    ],
    ex: [
      "She was tenacious in her pursuit of justice, even when everyone said to stop.",
      "The tenacious startup survived three near-bankruptcies before finding success.",
      "Ivy is tenacious — it will grow through concrete if you let it.",
    ],
    us: "Americans say absolute bulldog energy — tenacious is a huge compliment in hustle culture.",
    uk: "British speakers say dogged or she is a fighter.",
    syn: ["persistent", "determined", "stubborn", "relentless", "resolute"],
    fact: "From Latin tenax (holding fast) — same root as tenant and tenor. All about holding on tightly.",
    source: "lexicon",
  },
  sonder: {
    w: "sonder",
    ph: "/ˈsɒn.dər/",
    pos: "noun",
    d: [
      "The realization that each passerby has a life as vivid and complex as your own.",
      "A profound awareness of the depth of other people's inner lives.",
    ],
    ex: [
      "Sitting in a busy cafe, she was hit by sudden sonder watching the strangers around her.",
      "Sonder — the feeling when you realize everyone is the main character of their own story.",
      "He felt sonder on the subway, imagining entire lifetimes behind each face.",
    ],
    us: "Lives almost entirely in internet culture — Reddit, Tumblr, Pinterest quotes.",
    uk: "Very online word. Known by educated young British people but not in traditional vocabulary.",
    syn: ["empathy", "awareness", "perspective", "consciousness", "realization"],
    fact: "Invented by John Koenig for The Dictionary of Obscure Sorrows in 2012. Went viral because it named something everyone had felt but could not say.",
    source: "lexicon",
  },
  petrichor: {
    w: "petrichor",
    ph: "/ˈpet.rɪˌkɔːr/",
    pos: "noun",
    d: [
      "The pleasant, earthy smell that occurs when rain falls on dry earth.",
      "The distinctive scent associated with rain and wet soil environments.",
    ],
    ex: [
      "The petrichor after the summer storm made everyone stop and breathe deeply.",
      "There is nothing quite like petrichor after months of drought.",
      "She opened the window just to catch the petrichor drifting in from outside.",
    ],
    us: "Most Americans say that rain smell — but petrichor is gaining popularity fast.",
    uk: "British people are obsessed with the smell of rain — petrichor is increasingly known and loved.",
    syn: ["rain scent", "earth smell", "geosmin", "wet soil fragrance"],
    fact: "Coined in 1964 by Australian scientists. From Greek petra (stone) + ichor (the fluid in the veins of the gods).",
    source: "lexicon",
  },
  zeitgeist: {
    w: "zeitgeist",
    ph: "/ˈzaɪtˌɡaɪst/",
    pos: "noun",
    d: [
      "The defining spirit or mood of a particular period of history.",
      "The general intellectual, moral, and cultural climate of an era.",
    ],
    ex: [
      "TikTok has become the clearest mirror of the current cultural zeitgeist.",
      "The 1960s zeitgeist was defined by rebellion and questioning authority.",
      "That film perfectly captured the anxiety that defined the zeitgeist of its decade.",
    ],
    us: "Used constantly in media, marketing, and culture criticism in the US.",
    uk: "British journalists and critics use zeitgeist freely — fits intellectual British discourse.",
    syn: ["spirit of the age", "cultural mood", "era", "climate", "ethos"],
    fact: "Directly from German — Zeit (time) + Geist (spirit). Central to 19th century German philosophy, especially Hegel.",
    source: "lexicon",
  },
  ambivalent: {
    w: "ambivalent",
    ph: "/æmˈbɪv.ə.lənt/",
    pos: "adjective",
    d: [
      "Having mixed feelings or contradictory ideas about something.",
      "(Psychology) Simultaneously experiencing contradictory emotions toward a person or thing.",
    ],
    ex: [
      "She felt ambivalent about the promotion — excited, but not ready to give up her team.",
      "He was genuinely ambivalent about moving — so much to miss and so much to gain.",
      "His ambivalent relationship with his hometown shaped everything he wrote.",
    ],
    us: "Americans say I have mixed feelings or I am torn — ambivalent is often confused with indifferent.",
    uk: "British speakers say I am in two minds about it.",
    syn: ["conflicted", "torn", "undecided", "uncertain", "mixed"],
    fact: "Coined by Swiss psychiatrist Eugen Bleuler in 1910. True ambivalence means feeling two strong opposite things at once.",
    source: "lexicon",
  },
  pensive: {
    w: "pensive",
    ph: "/ˈpen.sɪv/",
    pos: "adjective",
    d: [
      "Engaged in deep or serious thought; thoughtfully sad.",
      "Dreamily or wistfully thoughtful; absorbed in reflection.",
    ],
    ex: [
      "She sat by the window in a pensive mood, watching the rain trace patterns on the glass.",
      "The photograph captured him in a rare pensive moment, looking out to sea.",
      "Music puts him in a pensive state where he does his best thinking.",
    ],
    us: "Americans say I am in my head right now or just zoning out and thinking.",
    uk: "British speakers love thoughtful and reflective in casual speech.",
    syn: ["thoughtful", "reflective", "meditative", "contemplative", "wistful"],
    fact: "From Old French pensif — from penser (to think), from Latin pensare (to weigh). Same root as ponder.",
    source: "lexicon",
  },
  catharsis: {
    w: "catharsis",
    ph: "/kəˈθɑː.sɪs/",
    pos: "noun",
    d: [
      "The process of releasing strong or repressed emotions for relief.",
      "(Ancient Greek theater) Emotional cleansing experienced by an audience through tragedy.",
    ],
    ex: [
      "Crying through that movie was exactly the catharsis she needed after a terrible week.",
      "Exercise became his catharsis after the breakup.",
      "Writing is catharsis — put the unbearable into words and it becomes bearable.",
    ],
    us: "Americans use catharsis freely in therapy culture — I needed that cry, so cathartic.",
    uk: "British speakers say good cry or getting it out of your system.",
    syn: ["release", "purging", "cleansing", "relief", "purification"],
    fact: "Aristotle invented the concept in his Poetics (335 BC) — watching tragedy let audiences safely release their own suppressed emotions.",
    source: "lexicon",
  },
  juxtapose: {
    w: "juxtapose",
    ph: "/ˈdʒʌk.stəˌpəʊz/",
    pos: "verb",
    d: [
      "To place two things side by side, especially for contrast or comparison.",
      "Juxtaposition: placing two contrasting things together to highlight their differences.",
    ],
    ex: [
      "The film juxtaposes extreme wealth and poverty to make its point without a word.",
      "I love how they juxtaposed the old architecture with the ultra-modern glass building.",
      "Her calm voice juxtaposed sharply with the chaos happening around her.",
    ],
    us: "Americans use juxtapose mostly in art and film criticism.",
    uk: "British speakers use juxtaposition naturally in journalism and cultural commentary.",
    syn: ["contrast", "compare", "set against", "place beside", "oppose"],
    fact: "Juxtaposition is used far more than the verb juxtapose — the noun form completely took over in popular usage.",
    source: "lexicon",
  },
  whimsical: {
    w: "whimsical",
    ph: "/ˈwɪm.zɪ.kəl/",
    pos: "adjective",
    d: [
      "Playfully quaint or fanciful, especially in an appealing way.",
      "Acting capriciously; subject to sudden changes of mood.",
    ],
    ex: [
      "Her apartment was filled with whimsical decorations — tiny doors painted on the walls.",
      "The architect's whimsical touch turned an ordinary building into something children loved.",
      "He had a whimsical sense of humor that caught people off guard in the best way.",
    ],
    us: "Americans say quirky, cute, or fairy-tale vibes — huge in Etsy and Pinterest culture.",
    uk: "British speakers use it naturally — fits the tradition of eccentric, charming, Roald Dahl-style imagination.",
    syn: ["playful", "fanciful", "quirky", "imaginative", "capricious"],
    fact: "Whim comes from Old Norse hvima meaning to wander with the eyes — following fancy rather than reason.",
    source: "lexicon",
  },
  profound: {
    w: "profound",
    ph: "/prəˈfaʊnd/",
    pos: "adjective",
    d: [
      "Very great or intense; having deep meaning or insight.",
      "(Of a state or emotion) thoroughgoing and far-reaching.",
    ],
    ex: [
      "The documentary had a profound effect on how she saw her own privilege.",
      "Sometimes the most profound truths come wrapped in the simplest sentences.",
      "Losing someone creates a profound shift in how you see time.",
    ],
    us: "Americans overuse profound — that hit different is the Gen Z casual equivalent.",
    uk: "British speakers are more reserved — quite moving saves profound for truly significant things.",
    syn: ["deep", "meaningful", "significant", "intense", "far-reaching"],
    fact: "From Latin profundus — pro (down) + fundus (bottom). Same root as fund and foundation. Reaching to the very bottom.",
    source: "lexicon",
  },
  eloquent: {
    w: "eloquent",
    ph: "/ˈel.ə.kwənt/",
    pos: "adjective",
    d: [
      "Fluent or persuasive in speaking or writing; clearly and powerfully expressive.",
      "Clearly expressing or indicating something without words.",
    ],
    ex: [
      "Her eloquent speech moved the entire audience to tears.",
      "He was too emotional to speak — his silence was more eloquent than any words.",
      "The lawyer made an eloquent case that changed the jury entirely.",
    ],
    us: "Americans say well-spoken or he has a way with words.",
    uk: "British speakers say very articulate or beautifully put — eloquent is a genuine compliment.",
    syn: ["articulate", "fluent", "expressive", "persuasive", "well-spoken"],
    fact: "From Latin eloqui — ex (out) + loqui (to speak). Same root as loquacious (too talkative) and ventriloquist (belly speaker).",
    source: "lexicon",
  },
  solitude: {
    w: "solitude",
    ph: "/ˈsɒl.ɪ.tjuːd/",
    pos: "noun",
    d: [
      "The state of being alone, often by choice and in peace.",
      "A lonely or uninhabited place.",
    ],
    ex: [
      "She craved solitude after months of constant social obligations.",
      "He did his best writing in the solitude of early mornings before the house woke up.",
      "The mountain cabin offered perfect solitude — no signal, no noise, just quiet.",
    ],
    us: "Americans say alone time or I need to recharge — solitude sounds more intentional and beautiful.",
    uk: "British speakers appreciate solitude culturally — it fits the tradition of long countryside walks alone.",
    syn: ["isolation", "seclusion", "privacy", "aloneness", "retreat"],
    fact: "From Latin solitudo — from solus (alone). Same root as solo, sole, and desolate. Solitude implies choice; loneliness implies lack.",
    source: "lexicon",
  },
  paradox: {
    w: "paradox",
    ph: "/ˈpær.ə.dɒks/",
    pos: "noun",
    d: [
      "A statement that seems contradictory but may actually be true.",
      "A person or thing that combines contradictory features or qualities.",
    ],
    ex: [
      "The paradox of choice — more options actually make us less happy.",
      "She was a walking paradox: fiercely independent yet deeply afraid of being alone.",
      "The city's paradox is that it feels loneliest despite millions of people around.",
    ],
    us: "Americans love paradox in philosophy and internet discussions.",
    uk: "British speakers use paradox naturally in debate, journalism, and academic writing.",
    syn: ["contradiction", "irony", "enigma", "puzzle", "oxymoron"],
    fact: "From Greek paradoxos — para (against) + doxa (opinion). A statement that goes against what everyone thinks, but turns out to be true.",
    source: "lexicon",
  },
  bittersweet: {
    w: "bittersweet",
    ph: "/ˌbɪt.əˈswiːt/",
    pos: "adjective",
    d: [
      "Being both pleasant and painful at the same time; evoking mixed emotions.",
      "A climbing plant with toxic berries that change color as they ripen.",
    ],
    ex: [
      "Graduation was bittersweet — the joy of achievement wrapped in the sadness of goodbye.",
      "Watching your child leave for college is the most bittersweet experience of parenthood.",
      "The song had a bittersweet quality that made you smile and ache at the same time.",
    ],
    us: "Americans use bittersweet constantly — especially for endings, goodbyes, and nostalgia.",
    uk: "British speakers love bittersweet — it captures the tendency to feel joy and sadness simultaneously.",
    syn: ["mixed", "poignant", "tender", "nostalgic", "wistful"],
    fact: "One of the rare English words that perfectly captures emotional complexity in just one word.",
    source: "lexicon",
  },
  schadenfreude: {
    w: "schadenfreude",
    ph: "/ˈʃɑːdənfrɔɪdə/",
    pos: "noun",
    d: [
      "Pleasure derived from another person's misfortune.",
      "A guilty delight in watching others fail or suffer consequences.",
    ],
    ex: [
      "There was a little schadenfreude watching the office bully trip over his own presentation.",
      "Watching reality TV is basically schadenfreude packaged as entertainment.",
      "She felt immediate schadenfreude when her rival's plan fell apart publicly.",
    ],
    us: "Americans love this word — feeling bad for laughing but laughing anyway is schadenfreude in real life.",
    uk: "British people practically invented the concept — dry enjoyment of others' misfortune is embedded in British humor.",
    syn: ["gloating", "malicious joy", "smugness", "satisfaction"],
    fact: "Directly from German — Schaden (damage) + Freude (joy). It entered English because there was no word for the concept. Psychologists say it is universal.",
    source: "lexicon",
  },
  labyrinth: {
    w: "labyrinth",
    ph: "/ˈlæb.ə.rɪnθ/",
    pos: "noun",
    d: [
      "A complicated irregular network of passages or paths; a maze.",
      "A complex and difficult situation; something intricate and hard to escape.",
    ],
    ex: [
      "The old city's backstreets were a labyrinth she happily got lost in for hours.",
      "Navigating the healthcare bureaucracy felt like a labyrinth with no exit.",
      "Inside the labyrinth of her own thoughts, she could not find a clear answer.",
    ],
    us: "Americans use labyrinth for bureaucracy and complex systems — this tax form is a literal labyrinth.",
    uk: "British speakers use labyrinth in both literal and metaphorical senses — very common in British literature.",
    syn: ["maze", "tangle", "network", "web", "complexity"],
    fact: "From Greek mythology — built by Daedalus to hold the Minotaur in Crete. It was so complex that even Daedalus almost could not escape.",
    source: "lexicon",
  },
  quintessential: {
    w: "quintessential",
    ph: "/ˌkwɪntɪˈsenʃəl/",
    pos: "adjective",
    d: [
      "Representing the most perfect or typical example of a quality or class.",
      "Of or relating to the most essential part of something; the purest form.",
    ],
    ex: [
      "The corner cafe was the quintessential Parisian experience — coffee and philosophy.",
      "He was the quintessential 90s kid — frosted tips, JNCO jeans, and a Tamagotchi.",
      "New York is the quintessential modern city, she wrote in her first postcard home.",
    ],
    us: "Americans use quintessential constantly — the quintessential American road trip is a very real sentence.",
    uk: "British speakers love it for archetypally British things — the quintessential English village.",
    syn: ["perfect example", "archetypal", "classic", "definitive", "typical"],
    fact: "From medieval philosophy — the quinta essentia (fifth essence) was the purest substance believed to make up the heavens, beyond earth, water, fire, and air.",
    source: "lexicon",
  },
  empathy: {
    w: "empathy",
    ph: "/ˈem.pə.θi/",
    pos: "noun",
    d: [
      "The ability to understand and share the feelings of another person.",
      "The capacity to place oneself in another position and feel what they feel.",
    ],
    ex: [
      "Great teachers lead with empathy — they remember what it felt like not to understand.",
      "Her empathy was her greatest strength and sometimes her greatest burden.",
      "The film works because it forces empathy toward characters you would normally dismiss.",
    ],
    us: "Americans say I feel you or I get it — empathy is core in US therapy and emotional intelligence culture.",
    uk: "British speakers value empathy but express it quietly — I understand or that must be hard.",
    syn: ["compassion", "understanding", "sensitivity", "feeling", "warmth"],
    fact: "Coined in 1909 by psychologist Edward Titchener — translated from German Einfuhlung (feeling into). Before empathy, English only had sympathy.",
    source: "lexicon",
  },
  aesthetic: {
    w: "aesthetic",
    ph: "/iːsˈθetɪk/",
    pos: "noun",
    d: [
      "A set of principles guiding the work of a particular artist or movement.",
      "Concerned with beauty or the appreciation of beauty; visually pleasing.",
    ],
    ex: [
      "Her whole apartment had a consistent dark academia aesthetic — books, candles, and deep green walls.",
      "The brand's aesthetic is minimal and clean, which is exactly why it works.",
      "He has an aesthetic eye — every photo he takes looks carefully planned.",
    ],
    us: "Aesthetic is huge in Gen Z culture — on TikTok and Pinterest it means any specific visual style or vibe.",
    uk: "British speakers use aesthetic in art and design contexts — the aesthetic of the piece is standard art criticism.",
    syn: ["style", "look", "visual identity", "beauty", "taste"],
    fact: "From Greek aisthetikos — perceptible by the senses. Originally philosophy about beauty. The internet turned it into a noun for a specific visual vibe.",
    source: "lexicon",
  },
  mundane: {
    w: "mundane",
    ph: "/mʌnˈdeɪn/",
    pos: "adjective",
    d: [
      "Lacking interest or excitement; dull and ordinary.",
      "Of this earthly world rather than a heavenly or spiritual one.",
    ],
    ex: [
      "She found beauty in mundane moments — waiting for the kettle, folding laundry in silence.",
      "The most creative minds often get ideas during mundane tasks like showering.",
      "He quit his mundane 9-to-5 and never looked back.",
    ],
    us: "Americans say basic, boring, or same old same old — mundane sounds more poetic.",
    uk: "British speakers say run of the mill or nothing special in casual speech.",
    syn: ["ordinary", "everyday", "routine", "dull", "commonplace"],
    fact: "From Latin mundus meaning world — originally meant of the physical world as opposed to heaven. Evolved to mean ordinary because the world is less exciting than paradise.",
    source: "lexicon",
  },
  tranquil: {
    w: "tranquil",
    ph: "/ˈtræŋkwɪl/",
    pos: "adjective",
    d: [
      "Free from disturbance; calm and peaceful.",
      "Undisturbed by noise, agitation, or distraction.",
    ],
    ex: [
      "The lake at dawn was completely tranquil — not a ripple, not a sound.",
      "She found tranquil moments by sitting with her coffee before anyone else woke up.",
      "The village had a tranquil charm that made city visitors instantly slow down.",
    ],
    us: "Americans say so peaceful or super calm vibes — tranquil sounds intentional and serene.",
    uk: "British speakers use tranquil naturally — especially describing the countryside.",
    syn: ["calm", "peaceful", "serene", "still", "quiet"],
    fact: "From Latin tranquillus — possibly from trans (beyond) + quietus (at rest). To be inherently still, beyond even the need for quiet.",
    source: "lexicon",
  },
  irony: {
    w: "irony",
    ph: "/ˈaɪrəni/",
    pos: "noun",
    d: [
      "The expression of meaning through language that normally signifies the opposite.",
      "A state of affairs that appears contrary to what one would naturally expect.",
    ],
    ex: [
      "The irony of writing a book about procrastination and then procrastinating on it was not lost on him.",
      "She moved to a quiet town to escape noise, and a music festival moved in next door.",
      "Verbal irony is saying great weather during a thunderstorm.",
    ],
    us: "Americans misuse irony constantly. Most things called ironic are just coincidental. Alanis Morissette wrote a song called Ironic with no actual irony in it.",
    uk: "British speakers are masters of irony — it is the backbone of British humor. Dry irony is practically a national language.",
    syn: ["sarcasm", "paradox", "contradiction", "wit", "satire"],
    fact: "From Greek eironeia — the word Socrates used for pretending ignorance to expose others' false knowledge. The original irony was a teaching method.",
    source: "lexicon",
  },
  pragmatic: {
    w: "pragmatic",
    ph: "/præɡˈmætɪk/",
    pos: "adjective",
    d: [
      "Dealing with things sensibly and realistically rather than following rigid rules.",
      "Focused on practical results over theory or ideology.",
    ],
    ex: [
      "She was pragmatic about the breakup — sad, but already thinking about what came next.",
      "A pragmatic approach to climate change means starting with what is actually achievable today.",
      "He was too pragmatic to romanticize failure — he just wanted to know what went wrong.",
    ],
    us: "Americans say realistic or practical — pragmatic is the businesslike, no-nonsense version.",
    uk: "British speakers appreciate pragmatism — let us be pragmatic about this is common in British politics.",
    syn: ["practical", "realistic", "sensible", "down-to-earth", "matter-of-fact"],
    fact: "From Greek pragma — a thing done. The philosophical movement Pragmatism was founded in America by William James. Truth is defined by what works in practice.",
    source: "lexicon",
  },
  candid: {
    w: "candid",
    ph: "/ˈkændɪd/",
    pos: "adjective",
    d: [
      "Truthful and straightforward; not hiding thoughts or feelings.",
      "(Of a photograph) taken informally, without the subject posing.",
    ],
    ex: [
      "She was refreshingly candid about her failures — no spin, no excuses.",
      "I will be candid with you: this project is behind and we need to talk about it.",
      "The candid photo caught him laughing genuinely for the first time in years.",
    ],
    us: "Americans say keeping it real or no filter — candid is the more refined, respectful version.",
    uk: "British speakers say frank or straight-talking — being too candid can feel blunt in British social culture.",
    syn: ["honest", "frank", "open", "straightforward", "transparent"],
    fact: "From Latin candidus meaning white or pure. Also the root of candidate — Romans wore white togas to signal honesty during elections.",
    source: "lexicon",
  },
  elusive: {
    w: "elusive",
    ph: "/ɪˈluːsɪv/",
    pos: "adjective",
    d: [
      "Difficult to find, catch, or achieve.",
      "Difficult to remember or describe clearly; hard to pin down.",
    ],
    ex: [
      "Success felt elusive — always just one more step away.",
      "The perfect word was elusive; she knew what she meant but could not find it.",
      "The snow leopard is one of the most elusive animals on earth — rarely seen by humans.",
    ],
    us: "Americans say hard to nail down or I cannot quite put my finger on it — elusive is the elegant version.",
    uk: "British speakers use elusive naturally in both literal and poetic senses.",
    syn: ["slippery", "fleeting", "hard to find", "intangible", "evasive"],
    fact: "From Latin eludere — to dodge or evade. Same root as illusion — something that tricks you into thinking you have grasped it.",
    source: "lexicon",
  },
  serene: {
    w: "serene",
    ph: "/sɪˈriːn/",
    pos: "adjective",
    d: [
      "Calm, peaceful, and untroubled; tranquil.",
      "(Of the sky or sea) clear and calm.",
    ],
    ex: [
      "Her serene expression during the chaos was either inspiring or slightly terrifying.",
      "The lake at sunrise was perfectly serene — glassy water reflecting pink clouds.",
      "He had a serene confidence that came from knowing exactly who he was.",
    ],
    us: "Americans say total zen, so peaceful, or calm vibes — serene sounds more elevated.",
    uk: "British speakers use serene to describe places especially — a serene stretch of English countryside.",
    syn: ["calm", "peaceful", "tranquil", "composed", "unruffled"],
    fact: "From Latin serenus — clear sky. A serene day was literally a cloudless one. Inner calm came from weather — a clear sky as a metaphor for an untroubled mind.",
    source: "lexicon",
  },
  intuition: {
    w: "intuition",
    ph: "/ˌɪntjuːˈɪʃən/",
    pos: "noun",
    d: [
      "The ability to understand something instinctively, without conscious reasoning.",
      "A feeling that guides you without a clear explanation for why.",
    ],
    ex: [
      "Her intuition told her not to take the job, and she was right.",
      "Trust your intuition — sometimes the gut knows what the brain has not caught up to yet.",
      "Good designers operate largely on intuition, refined by years of pattern recognition.",
    ],
    us: "Americans say gut feeling or I just had a feeling — intuition is the respected, scientific-sounding version.",
    uk: "British speakers say gut instinct or sixth sense — intuition is used in both formal and casual speech.",
    syn: ["instinct", "gut feeling", "sixth sense", "hunch", "insight"],
    fact: "From Latin intueri — to look at or contemplate. Intuition is the brain recognizing patterns too fast for conscious thought to follow — compressed experience.",
    source: "lexicon",
  },
  authentic: {
    w: "authentic",
    ph: "/ɔːˈθentɪk/",
    pos: "adjective",
    d: [
      "Of undisputed origin; genuine and real.",
      "Representing one's true nature or beliefs; true to oneself.",
    ],
    ex: [
      "Her authentic storytelling style connected with millions tired of polished fakeness.",
      "The restaurant felt authentic — not a tourist trap, but a real neighborhood spot.",
      "Being authentic in a world that rewards performance is genuinely difficult.",
    ],
    us: "Authentic is one of the most overused words in American marketing. It is also deeply valued in US therapy culture.",
    uk: "British speakers use authentic more sparingly — the real thing or the genuine article in casual speech.",
    syn: ["genuine", "real", "true", "original", "sincere"],
    fact: "From Greek authentes — one who acts independently, a master. The idea of self-authorship — being the author of your own life — is built into the word.",
    source: "lexicon",
  },
  vulnerable: {
    w: "vulnerable",
    ph: "/ˈvʌlnərəbəl/",
    pos: "adjective",
    d: [
      "Exposed to the possibility of being attacked or harmed, physically or emotionally.",
      "Open and willing to show one's true self, including weaknesses.",
    ],
    ex: [
      "Being vulnerable with someone for the first time is terrifying and necessary.",
      "The research showed that being vulnerable actually builds stronger trust than appearing perfect.",
      "She felt vulnerable after sharing her story publicly, but also lighter.",
    ],
    us: "Brene Brown made vulnerable a massive cultural keyword in the US — being vulnerable is now a leadership skill.",
    uk: "British speakers historically avoided vulnerability culturally — stiff upper lip — but attitudes are shifting.",
    syn: ["exposed", "open", "unguarded", "sensitive", "defenseless"],
    fact: "From Latin vulnerare — to wound. To be vulnerable literally means capable of being wounded — and accepting that is what makes deep connection possible.",
    source: "lexicon",
  },
  stoic: {
    w: "stoic",
    ph: "/ˈstəʊɪk/",
    pos: "adjective",
    d: [
      "Enduring pain or hardship without showing feelings or complaining.",
      "A person who endures pain without complaint; a follower of Stoicism.",
    ],
    ex: [
      "He was stoic throughout the surgery — not a grimace, not a sound.",
      "Her stoic response to the criticism made people respect her even more.",
      "Being stoic does not mean not feeling — it means not being controlled by what you feel.",
    ],
    us: "Americans use stoic to mean emotionally tough — huge in productivity and self-improvement culture. Marcus Aurelius is practically an internet celebrity now.",
    uk: "British stoicism is a cultural stereotype — keeping a stiff upper lip is the folk version of stoic philosophy.",
    syn: ["unemotional", "composed", "impassive", "enduring", "philosophical"],
    fact: "From the Greek Stoa Poikile — the Painted Porch in Athens where Zeno taught around 300 BC. The philosophy focused only on what you can control.",
    source: "lexicon",
  },
  charisma: {
    w: "charisma",
    ph: "/kəˈrɪzmə/",
    pos: "noun",
    d: [
      "A compelling attractiveness or charm that inspires devotion and admiration in others.",
      "(Theology) A divinely conferred power or talent.",
    ],
    ex: [
      "She walked into the room and the energy shifted — that is charisma.",
      "Great leaders do not just have good ideas — they have the charisma to make others believe in them.",
      "His charisma was so natural it seemed effortless, which made it even more powerful.",
    ],
    us: "Americans say magnetic, he just has IT, or star power — charisma is the more formal, respected version.",
    uk: "British speakers say very compelling or draws people in — charisma is widely understood and admired.",
    syn: ["charm", "magnetism", "presence", "appeal", "personality"],
    fact: "From Greek kharisma — a gift of grace from the gods. Originally a religious term. Max Weber brought it into social science in the 1900s.",
    source: "lexicon",
  },
  enigma: {
    w: "enigma",
    ph: "/ɪˈnɪɡmə/",
    pos: "noun",
    d: [
      "A person or thing that is mysterious, puzzling, or difficult to understand.",
      "A riddle or paradox.",
    ],
    ex: [
      "He was an enigma — warm with strangers, cold with those who loved him most.",
      "The Mona Lisa expression is history's most famous enigma.",
      "She is a complete enigma — no clear motive, no alibi, and somehow no fingerprints.",
    ],
    us: "Americans say she is a mystery or I cannot figure him out — enigma is the classier, more intriguing version.",
    uk: "British speakers use enigma naturally — it fits the British love of mystery novels and psychological complexity.",
    syn: ["mystery", "puzzle", "riddle", "paradox", "conundrum"],
    fact: "The ENIGMA machine — used by Nazi Germany to encode messages in WWII — was named after this word. Breaking it at Bletchley Park, largely by Alan Turing, is one of the greatest intellectual feats in history.",
    source: "lexicon",
  },
  catalyst: {
    w: "catalyst",
    ph: "/ˈkætəlɪst/",
    pos: "noun",
    d: [
      "A person or thing that precipitates an event or change.",
      "(Chemistry) A substance that increases the rate of a reaction without being consumed.",
    ],
    ex: [
      "The protest was the catalyst for a national conversation that had been overdue for decades.",
      "Meeting her mentor was the catalyst that turned a hobby into a career.",
      "Sometimes a crisis is the catalyst you did not know you needed.",
    ],
    us: "Americans love catalyst in business and startup culture — what was the catalyst for this idea?",
    uk: "British speakers use catalyst in both scientific and metaphorical senses comfortably.",
    syn: ["trigger", "spark", "impulse", "stimulus", "driving force"],
    fact: "From Greek katalysis — kata (down) + lyein (to loosen). A catalyst lowers the energy barrier for a reaction — it does not cause it, it makes it easier to happen.",
    source: "lexicon",
  },
  sanctuary: {
    w: "sanctuary",
    ph: "/ˈsæŋktʃuəri/",
    pos: "noun",
    d: [
      "A place of refuge or safety.",
      "A nature reserve; a place where birds or wildlife are protected.",
    ],
    ex: [
      "Her bedroom was her sanctuary — the one place where other people's needs could not follow her.",
      "The library became his sanctuary during the worst years of his life.",
      "They turned the old farmhouse into a wildlife sanctuary for injured animals.",
    ],
    us: "Americans use sanctuary city (political), sanctuary (personal refuge), and animal sanctuary all regularly.",
    uk: "British speakers say safe haven or refuge in casual speech — sanctuary sounds more spiritual or formal.",
    syn: ["refuge", "haven", "shelter", "retreat", "safe place"],
    fact: "From Latin sanctuarium — a holy place. Medieval churches offered right of sanctuary — criminals who reached the church could not be arrested. This lasted in England until 1623.",
    source: "lexicon",
  },
  clarity: {
    w: "clarity",
    ph: "/ˈklærɪti/",
    pos: "noun",
    d: [
      "The quality of being coherent, intelligible, and easy to understand.",
      "The quality of being transparent or pure; clearness.",
    ],
    ex: [
      "Writing things down gave her clarity she could not find just by thinking.",
      "He spoke with such clarity that even the most complex ideas felt simple.",
      "After weeks of confusion, one conversation gave her complete clarity about what she wanted.",
    ],
    us: "Americans use clarity constantly in self-help, therapy, and business — I need clarity on this is a standard professional phrase.",
    uk: "British speakers say clear as day or crystal clear in casual speech — clarity is used in formal writing.",
    syn: ["clearness", "transparency", "simplicity", "precision", "lucidity"],
    fact: "From Latin claritas — brightness, fame. Same root as clarinet (the clear instrument) and declare. Clarity is being bright and clear like a clean window letting full light through.",
    source: "lexicon",
  },
  integrity: {
    w: "integrity",
    ph: "/ɪnˈteɡrɪti/",
    pos: "noun",
    d: [
      "The quality of being honest and having strong moral principles.",
      "The state of being whole and undivided; structural soundness.",
    ],
    ex: [
      "She resigned rather than compromise her integrity — some things are not for sale.",
      "The integrity of the data is critical before we make any decisions.",
      "Real integrity means doing the right thing even when no one is watching.",
    ],
    us: "Americans use integrity in leadership culture, sports, and politics — a person of integrity is high praise.",
    uk: "British speakers say principled or a person of good character — integrity has a slightly formal ring.",
    syn: ["honesty", "principle", "honor", "decency", "wholeness"],
    fact: "From Latin integritas — wholeness. Same root as integer (a whole number) and integrate. A person of integrity is literally an undivided, whole person.",
    source: "lexicon",
  },
  ambiguous: {
    w: "ambiguous",
    ph: "/æmˈbɪɡjuəs/",
    pos: "adjective",
    d: [
      "Open to more than one interpretation; having a double meaning.",
      "Unclear or inexact because a choice between alternatives has not been made.",
    ],
    ex: [
      "The ending of the film was deliberately ambiguous — no one agreed on what it meant.",
      "Her smile was ambiguous — was it warm or was it threatening?",
      "The contract clause was ambiguous enough to cause a year of legal disputes.",
    ],
    us: "Americans say it is up to interpretation or that is vague — ambiguous is the precise version.",
    uk: "British speakers use ambiguous naturally in both legal and everyday contexts.",
    syn: ["unclear", "vague", "uncertain", "open-ended", "equivocal"],
    fact: "From Latin ambiguus — from ambigere (to wander around). Ambi means both, agere means to drive — being driven in both directions at once. Same root as ambidextrous.",
    source: "lexicon",
  },
  flamboyant: {
    w: "flamboyant",
    ph: "/flæmˈbɔɪənt/",
    pos: "adjective",
    d: [
      "Tending to attract attention because of exuberance, confidence, and bright appearance.",
      "(Architecture) Characterized by wavy, flame-like curves.",
    ],
    ex: [
      "His flamboyant style — feather boa, platform boots — made him impossible to ignore.",
      "She gave a flamboyant performance that had the whole crowd on their feet.",
      "The drag queen's flamboyant entrance stopped every conversation in the room.",
    ],
    us: "Americans say extra, over the top, or giving main character energy — flamboyant is the classic version.",
    uk: "British speakers use flamboyant to describe eccentric, bold personalities — usually with admiration.",
    syn: ["showy", "extravagant", "bold", "theatrical", "vivid"],
    fact: "From French flamboyer — to flame. Originally described late Gothic architecture where stonework looked like dancing flames. The visual energy of fire became a metaphor for people who burn bright.",
    source: "lexicon",
  },
  gregarious: {
    w: "gregarious",
    ph: "/ɡrɪˈɡeəriəs/",
    pos: "adjective",
    d: [
      "Fond of company; sociable and enjoying being part of a group.",
      "(Of animals) living in flocks or colonies.",
    ],
    ex: [
      "She was so gregarious that she could make friends in an elevator.",
      "He envied her gregarious nature — socializing drained him but seemed to energize her.",
      "Dolphins are famously gregarious — they live, hunt, and play in social pods.",
    ],
    us: "Americans say super social, a people person, or life of the party — gregarious is the sophisticated version.",
    uk: "British speakers say very sociable or loves company — gregarious sounds slightly formal but affectionate.",
    syn: ["sociable", "outgoing", "friendly", "extroverted", "convivial"],
    fact: "From Latin gregarius — from grex (flock or herd). Same root gives us congregation (gathered flock) and aggregate (gathered together).",
    source: "lexicon",
  },
  hubris: {
    w: "hubris",
    ph: "/ˈhjuːbrɪs/",
    pos: "noun",
    d: [
      "Excessive pride or self-confidence, especially in a way that leads to downfall.",
      "(Greek tragedy) The fatal overconfidence of the hero that brings about their destruction.",
    ],
    ex: [
      "His hubris was his undoing — he was so sure he could not fail that he stopped preparing.",
      "There is a certain hubris in thinking you can control everything.",
      "The hubris of Silicon Valley is believing technology is always the answer.",
    ],
    us: "Americans use hubris in political commentary and business criticism — especially when powerful people collapse spectacularly.",
    uk: "British speakers love hubris — it fits the long tradition of watching the powerful fall.",
    syn: ["arrogance", "overconfidence", "pride", "conceit", "ego"],
    fact: "Directly from Greek — hubris was a specific crime in ancient Athens: deliberately humiliating someone. The gods punished hubris with nemesis — divine retribution.",
    source: "lexicon",
  },
  idyllic: {
    w: "idyllic",
    ph: "/ɪˈdɪlɪk/",
    pos: "adjective",
    d: [
      "Like an idyll; extremely happy, peaceful, or picturesque.",
      "Resembling a simple, perfect scene of nature or rural life.",
    ],
    ex: [
      "The village looked idyllic on the surface, but everyone knew its secrets.",
      "They spent an idyllic summer traveling with no plans and no deadlines.",
      "The photos made it look idyllic — the reality was mosquitoes and a broken fan.",
    ],
    us: "Americans say picture perfect or like something out of a movie — idyllic is the more poetic version.",
    uk: "British speakers use idyllic naturally for countryside and village life.",
    syn: ["perfect", "peaceful", "blissful", "paradise-like", "picturesque"],
    fact: "From Greek eidyllion — a short poem about country life. Ancient Greek poets wrote idylls — short, idealized scenes of rural peace. The form became a metaphor for perfect simplicity.",
    source: "lexicon",
  },
  karma: {
    w: "karma",
    ph: "/ˈkɑːmə/",
    pos: "noun",
    d: [
      "(In Hinduism and Buddhism) The sum of a person's actions, determining future fate.",
      "In popular use: what goes around comes around.",
    ],
    ex: [
      "She did not need to get revenge — she believed in karma and left it to the universe.",
      "That is karma — he treated everyone badly and now nobody showed up for him.",
      "Good karma: helped a stranger. Bad karma: immediately spilled coffee on myself.",
    ],
    us: "Karma is everywhere in American pop culture — Taylor Swift, Reddit, daily conversation. People use it constantly.",
    uk: "British speakers use karma casually — serves him right, that is karma is a common phrase.",
    syn: ["fate", "destiny", "cosmic justice", "consequence", "what goes around"],
    fact: "From Sanskrit karman — action or deed. In original Hindu and Buddhist philosophy karma is neutral — the law of cause and effect. The Western version simplified it into moral payback.",
    source: "lexicon",
  },
  lethargic: {
    w: "lethargic",
    ph: "/ləˈθɑːdʒɪk/",
    pos: "adjective",
    d: [
      "Affected by lethargy; sluggish, slow, and lacking energy or enthusiasm.",
      "Relating to or suffering from the state of lethargy.",
    ],
    ex: [
      "She felt lethargic all week — not sick exactly, just running on empty.",
      "The heat made everyone lethargic; even the dogs stopped barking by noon.",
      "Monday morning meetings are lethargic by design, apparently.",
    ],
    us: "Americans say no energy, dragging, or literally cannot function — lethargic is the medical-sounding version.",
    uk: "British speakers say sluggish or cannot be bothered — lethargic fits naturally into British understatement.",
    syn: ["sluggish", "tired", "listless", "slow", "torpid"],
    fact: "From Greek lethe — the river of forgetfulness in the underworld. Souls drank from Lethe before reincarnation to forget their past lives. Being lethargic was like being half-drowned in forgetting.",
    source: "lexicon",
  },
  maverick: {
    w: "maverick",
    ph: "/ˈmævərɪk/",
    pos: "noun",
    d: [
      "An independent-minded person who does not follow the crowd; a nonconformist.",
      "Independent in thought and action; unconventional.",
    ],
    ex: [
      "She was a maverick in the industry — ignoring trends and building something entirely her own.",
      "The maverick scientist pursued the theory everyone else dismissed, and turned out to be right.",
      "Top Gun made maverick a cultural shorthand for reckless brilliance.",
    ],
    us: "Americans love maverick — it carries connotations of independence, the wild west, and American individualism.",
    uk: "British speakers use maverick for unconventional thinkers — often in science, politics, or sport.",
    syn: ["nonconformist", "rebel", "independent", "free spirit", "individualist"],
    fact: "Named after Samuel Maverick (1803-1870), a Texas rancher who refused to brand his cattle. His name became a word for anything that refuses to be marked or categorized.",
    source: "lexicon",
  },
  nuance: {
    w: "nuance",
    ph: "/ˈnjuːɑːns/",
    pos: "noun",
    d: [
      "A subtle difference in or shade of meaning, expression, or sound.",
      "The quality of being subtle, complex, and having many dimensions.",
    ],
    ex: [
      "The debate was too nuanced for a tweet — both sides were right in different ways.",
      "She was a director who understood nuance — the difference between sad and devastated.",
      "The internet has no nuance, he complained, deleting his account for the third time.",
    ],
    us: "Nuance is a huge word in American political and academic discourse — it is nuanced means the simple take is wrong.",
    uk: "British speakers value nuance deeply — it fits the tendency toward understatement and qualification.",
    syn: ["subtlety", "shade", "distinction", "complexity", "gradation"],
    fact: "From French nuer — to shade. From Latin nubes — cloud. A nuance is literally a shade of cloud — the difference between one grey sky and another.",
    source: "lexicon",
  },
  obsolete: {
    w: "obsolete",
    ph: "/ˌɒbsəˈliːt/",
    pos: "adjective",
    d: [
      "No longer produced or used; out of date.",
      "(Biology) Vestigial; imperfectly developed or no longer functional.",
    ],
    ex: [
      "The fax machine is not obsolete everywhere — Japan still uses it constantly.",
      "His skills were not obsolete, just ahead of their time.",
      "DVDs went from dominant to obsolete in about fifteen years.",
    ],
    us: "Americans say dead, nobody uses that anymore, or so last decade — obsolete is the formal version.",
    uk: "British speakers say out of date, antiquated, or past it in casual speech.",
    syn: ["outdated", "outmoded", "archaic", "extinct", "superseded"],
    fact: "From Latin obsolescere — to grow old, to fall into disuse. A word, technology, or idea becomes obsolete the same way ruins do — gradually, then all at once.",
    source: "lexicon",
  },
  platonic: {
    w: "platonic",
    ph: "/pləˈtɒnɪk/",
    pos: "adjective",
    d: [
      "(Of love or friendship) intimate and affectionate but not sexual.",
      "Relating to Plato or his philosophy.",
    ],
    ex: [
      "They were perfectly clear it was platonic — close friends who happened to talk every day.",
      "Can men and women have platonic friendships? The question that launches a thousand arguments.",
      "Platonic ideals in philosophy means the perfect, abstract form of a thing beyond what the senses can perceive.",
    ],
    us: "Americans use platonic to clarify non-romantic close friendships — we are just platonic is common.",
    uk: "British speakers use platonic similarly — also used in academic philosophy discussions.",
    syn: ["non-romantic", "friendly", "intellectual", "spiritual", "pure"],
    fact: "Named after Plato, who described a form of love based on the pursuit of beauty and wisdom — not physical desire. His Symposium described love rising from the body to the soul to wisdom itself.",
    source: "lexicon",
  },
  rhetoric: {
    w: "rhetoric",
    ph: "/ˈretərɪk/",
    pos: "noun",
    d: [
      "The art of effective or persuasive speaking or writing.",
      "In modern use: language designed to persuade, often regarded as showy or lacking substance.",
    ],
    ex: [
      "His speech was all rhetoric — passionate, beautiful, and completely empty of actual policy.",
      "Rhetoric is the oldest subject ever taught — ancient Greeks considered it essential for citizenship.",
      "She cut through the rhetoric and asked what was actually being promised.",
    ],
    us: "Americans use rhetoric negatively — that is just rhetoric means it sounds good but means nothing.",
    uk: "British speakers use rhetoric both positively (the skill) and negatively (the emptiness) — context matters.",
    syn: ["oratory", "persuasion", "language", "spin", "discourse"],
    fact: "Aristotle identified three pillars: ethos (credibility), pathos (emotion), and logos (logic). Every political speech, advertisement, and sermon still uses exactly these three tools.",
    source: "lexicon",
  },
  surreal: {
    w: "surreal",
    ph: "/səˈriːəl/",
    pos: "adjective",
    d: [
      "Having the qualities of surrealism; bizarre, dreamlike, and unsettling.",
      "So unusual or strange as to feel unreal.",
    ],
    ex: [
      "Standing on the summit was surreal — I had imagined it so long it did not feel real when it happened.",
      "The trial had a surreal quality — absurd and serious at the exact same time.",
      "2020 was just collectively surreal — nothing felt possible, then everything happened.",
    ],
    us: "Americans use surreal for anything dreamlike or hard to process — this is surreal is a common reaction to major life moments.",
    uk: "British speakers use surreal naturally — Monty Python made surreal humor a British cultural institution.",
    syn: ["dreamlike", "bizarre", "otherworldly", "strange", "uncanny"],
    fact: "From surrealism — the 1920s art movement led by Andre Breton. Sur means above — surreal means above reality. Salvador Dali and Rene Magritte made surreal a visual style before it became a feeling.",
    source: "lexicon",
  },
  momentum: {
    w: "momentum",
    ph: "/məˈmentəm/",
    pos: "noun",
    d: [
      "The force or impetus of a movement or series of events.",
      "(Physics) The quantity of motion of a moving body — mass times velocity.",
    ],
    ex: [
      "Once the campaign gained momentum, it was impossible to stop.",
      "Losing momentum in the middle of a project is more dangerous than never starting.",
      "Newton's first law: momentum continues until something interrupts it.",
    ],
    us: "Momentum is everywhere in American sports, business, and politics — we have momentum is a battle cry.",
    uk: "British speakers use momentum in sports and politics — building momentum is standard journalistic language.",
    syn: ["impetus", "force", "drive", "energy", "velocity"],
    fact: "From Latin movimentum — movement. Same root as motion, moment, and motor. In physics, momentum is conserved — it never disappears, only transfers.",
    source: "lexicon",
  },
  spontaneous: {
    w: "spontaneous",
    ph: "/spɒnˈteɪniəs/",
    pos: "adjective",
    d: [
      "Performed or occurring as a result of impulse, without planning.",
      "(Of a process) occurring without apparent external cause.",
    ],
    ex: [
      "The road trip was entirely spontaneous — they left at midnight with no destination.",
      "Her laughter was spontaneous and completely unguarded, which made it contagious.",
      "Spontaneous combustion is rare but real — it happens when heat builds faster than it can escape.",
    ],
    us: "Americans romanticize spontaneity — just go for it and no plans culture is deeply American.",
    uk: "British speakers appreciate spontaneity but planning ahead is more culturally respected.",
    syn: ["impulsive", "unplanned", "natural", "instinctive", "unprompted"],
    fact: "From Latin sponte — of one's own accord, freely. The same root as respond — both involve acting from within, without being forced.",
    source: "lexicon",
  },
  introspective: {
    w: "introspective",
    ph: "/ˌɪntrəˈspektɪv/",
    pos: "adjective",
    d: [
      "Examining one's own thoughts, feelings, and motives.",
      "Characterized by or given to reflection and self-examination.",
    ],
    ex: [
      "She was deeply introspective — journals filled every shelf of her room.",
      "The album has an introspective quality that hits differently at 3am than at noon.",
      "After the failure, he became introspective for months before deciding what to do next.",
    ],
    us: "Americans value introspection in therapy culture — doing the inner work is the casual version.",
    uk: "British speakers tend to be introspective quietly — diaries, long walks, and understatement.",
    syn: ["reflective", "self-examining", "thoughtful", "meditative", "inward-looking"],
    fact: "From Latin introspicere — intro (within) + specere (to look). Same specere root gives us spectator, inspect, and expect. To be introspective is to be your own audience.",
    source: "lexicon",
  },
  cynical: {
    w: "cynical",
    ph: "/ˈsɪnɪkəl/",
    pos: "adjective",
    d: [
      "Believing that people are motivated purely by self-interest; distrustful of human sincerity.",
      "Concerned only with self-interest; not caring about moral principles.",
    ],
    ex: [
      "She was too cynical to believe the apology was genuine — she had heard it all before.",
      "Years in politics had made him deeply cynical about whether anything ever really changed.",
      "A cynical ad campaign that pretended to care about the environment while doing nothing.",
    ],
    us: "Americans say I am not buying it or yeah right — cynical describes the permanent state of many Americans toward institutions.",
    uk: "British people are culturally quite cynical — irony and skepticism are built into the national character.",
    syn: ["skeptical", "distrustful", "pessimistic", "jaded", "doubtful"],
    fact: "From the ancient Greek Cynics — philosophers who rejected social norms. Diogenes lived in a barrel and told Alexander the Great to get out of his sunlight. Their blunt rejection of society gave us the modern meaning.",
    source: "lexicon",
  },
  verbose: {
    w: "verbose",
    ph: "/vɜːˈbəʊs/",
    pos: "adjective",
    d: [
      "Using or expressed in more words than are needed; unnecessarily long-winded.",
      "Characterized by an excess of words relative to the idea being conveyed.",
    ],
    ex: [
      "His emails were verbose — three paragraphs where one sentence would have done.",
      "The novel is beautiful, but the middle third is too verbose to finish in one sitting.",
      "She asked him to stop being verbose and just say what he wanted.",
    ],
    us: "Americans say get to the point or TL;DR — verbose is the polite professional version.",
    uk: "British speakers say rather long-winded or could have been shorter — verbose is slightly formal.",
    syn: ["wordy", "long-winded", "rambling", "prolix", "garrulous"],
    fact: "From Latin verbum — word. Same root as verb, verbal, and proverb. A verbose person is, quite literally, made of too many words.",
    source: "lexicon",
  },
  vague: {
    w: "vague",
    ph: "/veɪɡ/",
    pos: "adjective",
    d: [
      "Of uncertain, indefinite, or unclear character or meaning.",
      "Thinking or communicating without precision; hard to pin down.",
    ],
    ex: [
      "His plan was vague at best — lots of enthusiasm, very few specifics.",
      "She had a vague feeling that something was about to change.",
      "The instructions were so vague that nobody built the same thing.",
    ],
    us: "Americans say wishy-washy, unclear, or he is not saying anything — vague is the everyday word.",
    uk: "British speakers say a bit woolly or not very clear — vague is universally understood.",
    syn: ["unclear", "indefinite", "hazy", "imprecise", "ambiguous"],
    fact: "From Latin vagus — wandering, straying. Same root as vagabond and the vagus nerve. A vague idea is one that has not decided where to settle.",
    source: "lexicon",
  },
};

export const ALL = Object.keys(W);

export const FEATURED = [
  "ephemeral",
  "serendipity",
  "petrichor",
  "sonder",
  "schadenfreude",
  "surreal",
  "liminal",
  "wanderlust",
];

export const DEFAULT_COLS = [
  { id: 1, name: "Daily Words", emoji: "📅", col: "#2F6FED" },
  { id: 2, name: "Slang", emoji: "✦", col: "#C07828" },
  { id: 3, name: "Formal English", emoji: "§", col: "#4A6FA5" },
  { id: 4, name: "Idioms", emoji: "※", col: "#3D7A5A" },
];

export const COL_MARKS = ["✦", "※", "§", "○", "◇", "△", "□", "☆", "♣", "♪", "∞", "◎"];

export const COL_COLORS = [
  "#2F6FED",
  "#C07828",
  "#4A6FA5",
  "#3D7A5A",
  "#8B4A4A",
  "#5B5A7A",
  "#3A7A8A",
  "#6A5A3A",
];

export function suggest(q: string, extra: string[] = []): string[] {
  const l = q.toLowerCase().trim();
  if (!l) return [];
  const pool = Array.from(new Set([...ALL, ...extra]));
  const starts = pool.filter((w) => w.toLowerCase().startsWith(l));
  const contains = pool.filter(
    (w) => !w.toLowerCase().startsWith(l) && w.toLowerCase().includes(l),
  );
  return [...starts, ...contains].slice(0, 8);
}

export function shortDef(entry: WordEntry): string {
  const s = entry.d[0] ?? "";
  return s.length > 72 ? s.slice(0, 69) + "…" : s;
}

export function todayLabel(): string {
  return new Date().toLocaleDateString("en-US", { month: "short", day: "numeric" });
}

export function hexToRgb(h: string): string {
  const x = h.replace("#", "");
  const n =
    x.length === 3
      ? x
          .split("")
          .map((c) => c + c)
          .join("")
      : x;
  const r = parseInt(n.slice(0, 2), 16);
  const g = parseInt(n.slice(2, 4), 16);
  const b = parseInt(n.slice(4, 6), 16);
  return `${r}, ${g}, ${b}`;
}
